name: Auto-merge Pack PRs

on:
  pull_request:
    branches: [main]
    paths: ['pax/**']
    types: [opened, reopened, synchronize]

permissions:
  pull-requests: write
  contents: write

jobs:
  enable-automerge:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'community') }}
    steps:
      - name: Enable auto-merge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
